### ISSUE TITLE
add demo to preview how to plugin work

### ISSUE THREAD

**Issue by osman-mohamad** [HosseinAgha/persian-katex-plugin#4]

**Comment by HosseinAgha** [comment]
Currently I don’t have bandwidth for this but contributions for a gh-pages site are welcome.  
You can easily try it using ‘npm run dev’

**Comment by HosseinAgha** [comment]
@osman-mohamad I added the demo website :) check it out  
https://hosseinagha.github.io/persian-katex-plugin/

**Comment by osman-mohamad** [comment]
thank you @HosseinAgha
